// <auto-generated />
namespace RedLine.Dal.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.2")]
    public sealed partial class AutoMuestraSeed : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AutoMuestraSeed));
        
        string IMigrationMetadata.Id
        {
            get { return "202605312248236_AutoMuestraSeed"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
