// <auto-generated />
namespace RedLine.Dal.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.2")]
    public sealed partial class DVCambios2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DVCambios2));
        
        string IMigrationMetadata.Id
        {
            get { return "202607111220167_DVCambios2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
